### ISSUE TITLE
slab性能测试

### ISSUE THREAD

**Issue by chuang0721** [baishancloud/lua-sharedtable#55]

**Comment by lishulong** [comment]
（1）单进程slab vs 单进程单线程malloc和free
（2）多进程slab vs 多线程malloc和free

**Comment by liubaohai** [comment]
之前有过cpu性能调优的经验，使用的是libprofile，如果感觉可以使用，可以参考这里面的例子https://shimo.im/doc/6e7PNLR7x9MPOEVV?r=4D0QK7

**Comment by lishulong** [comment]
@liubaohai 石墨文档没有访问权限

**Comment by lishulong** [comment]
346445591d7f2651020aa80a8fee9c6b44bc7ec3

done.
